apiVersion: v1
data:
  application-prod.properties: |
    # This Options will be changed by helm configmap
    ###############
    # log options #
    ###############
    logging.config=/home/mlplatform/logback-prod.xml
    logging.file.path={{ .Values.backend.volume.mountPath }}/log

    ####################
    # database options #
    ####################
    spring.datasource.url=jdbc:sqlite:{{ .Values.backend.volume.mountPath }}/prod.db

    ###############
    # jpa options #
    ###############
    spring.jpa.show-sql=false
    spring.jpa.hibernate.ddl-auto=none

    ######################
    # mlplatform options #
    ######################
    mlplatform.server.addr=http://mlplatform-backend-svc:18080
    mlplatform.server.base-path=/home/mlplatform
    mlplatform.server.private-mode={{ .Values.backend.private }}

    #####################
    # hyperdata options #
    #####################
    hyperdata.server.addr={{ .Values.hyperdata.address }}
    # ishttps는 현재 사용하지 않는 변수입니다.
    hyperdata.server.ishttps=false
    hyperdata.image.private.repository={{ .Values.registry.address }}
    hyperdata.image.private.secret={{ .Values.registry.secret }}
    
    ##########################
    # virtualization options #
    ##########################
    virtualization.server.addr=http://hyperdata-virtualization-svc:8100

    ###################
    # proAuth options #
    ###################
    proAuth.server.addr={{ .Values.proauth.address }}

    ######################
    # kubernetes options #
    ######################
    kubernetes.config.type=kubernetes
    kubernetes.config.ip={{ .Values.kubernetes.istio.ingressgateway.ip }}
    kubernetes.config.port={{ .Values.kubernetes.istio.ingressgateway.port }}
    kubernetes.config.namespace={{ .Release.Namespace }}
    kubernetes.config.serviceaccount-name=mlplatform-backend-sa
    kubernetes.config.storageclass={{ .Values.backend.volume.storageClass }}
    kubernetes.config.pvc-mount-path={{ .Values.backend.volume.mountPath }}

    #################
    # automl option #
    #################
    automl.image.name={{ .Values.automl.image.name }}:{{ .Values.automl.image.tag }}
    
    #################
    # mllab option #
    #################
    mllab.image.tensorflow1={{ .Values.mllab.image.tensorflow1.name }}:{{ .Values.mllab.image.tensorflow1.tag }}
    mllab.image.tensorflow2={{ .Values.mllab.image.tensorflow2.name }}:{{ .Values.mllab.image.tensorflow2.tag }}
    mllab.image.pytorch={{ .Values.mllab.image.pytorch.name }}:{{ .Values.mllab.image.pytorch.tag }}
    mllab.image.statistic-analysis={{ .Values.mllab.image.statisticAnalysis.name }}:{{ .Values.mllab.image.statisticAnalysis.tag }}

kind: ConfigMap
metadata:
  name: mlplatform-backend-deploy-configmap
