#!/bin/bash

REPOSITORY_URL=192.1.1.92:5000
VERSION=20220706_v1
IMAGE_NAME=hyperdata20.4.0.2.0_nifi

docker build -t $IMAGE_NAME:$VERSION .

docker tag $IMAGE_NAME:$VERSION $REPOSITORY_URL/$IMAGE_NAME:$VERSION

docker push $REPOSITORY_URL/$IMAGE_NAME:$VERSION
