apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hyperdata-mlplatform-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /automl/$2
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-response-headers: hdProjectName, hdUserRole, hdAdminRole, hdDBARole, hdManagementPermission, hdUsableDataPermission, hdMlLabPermission
    nginx.ingress.kubernetes.io/auth-url: "http://hyperdata-system-svc.{{ .Release.Namespace }}.svc.cluster.local:8100/hyperdata/api/v1/gateway/auth"
spec:
  tls:
    - secretName: istio.{{ .Release.Namespace }}-nginx-ingress-nginx
  rules:
   -  http:
        paths:
        - path: /hyperdata20(/|$)automl/(.*)
          pathType: Prefix
          backend:
            serviceName: mlplatform-backend-svc
            servicePort: {{ .Values.server.port }}

