apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hyperdata-virtualization-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.proxy.bodysize }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.proxy.timeout }}"
spec:
  tls:
    - secretName: istio.hyperdata-nginx-ingress-nginx
  rules:
    - http:
        paths:
          - path: /hyperdata{{ .Values.version.major  }}/projects/(.*)
            backend:
              serviceName: hyperdata-virtualization-svc
              servicePort: 8500
    - http:
        paths:
          - path: /hyperdata{{ .Values.version.major  }}/dataobjects/(.*)
            backend:
              serviceName: hyperdata-virtualization-svc
              servicePort: 8500