name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has not seen recent activity. Remove stale label or comment or this will be closed.'
        #stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'stale'
        #stale-pr-label: 'no-pr-activity'
        exempt-issue-labels: 'enhancement,bug,help wanted,'
        debug-only: false
