name: Test-LDAP

on:
  push:
  pull_request:
    
jobs:
  test-ldap:
    name: Test NiFi Helm Chart LDAP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.20.0'
          kubernetes version: 'v1.20.2'
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add dysnix https://dysnix.github.io/charts/
          helm repo update
          helm dep up
      - name: Install openldap
        run: |
          kubectl apply -f tests/03-ldap
          kubectl wait --for=condition=Ready pod --selector=app.kubernetes.io/name=openldap --timeout=5m
      - name: Install Nifi
        run: helm install nifi . -f tests/03-ldap-values.yaml
      - name: Check deployment status
        run: kubectl wait --for=condition=Ready pod/nifi-0 --timeout=20m
      - name: Wait for NiFi web server to start
        run: |
          for n in [ 0 1 2 3 4 5 6 7 8 9 ]
          do
            if kubectl logs pod/nifi-0 -c app-log | grep 'JettyServer NiFi has started'
            then
              exit 0
            fi
            sleep 30
          done
          echo NiFi did not start for 300 seconds!
          exit 1
      - name: Check that LDAP login works
        run: |
          kubectl exec nifi-0 -c server -- curl -d username=user1 -d password=password1 -sk https://localhost:8443/nifi-api/access/token | \
            grep -v 'The supplied username and password are not valid.'
      - name: Check that LDAP incorrect password fails
        run: |
          kubectl exec nifi-0 -c server -- curl -d username=user1 -d password=password2 -sk https://localhost:8443/nifi-api/access/token | \
            grep 'The supplied username and password are not valid.'
 