apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gdb-ingress-bolt
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  tls:
    - secretName: istio.hyperdata-nginx-ingress-nginx
  rules:
   -  http:
       paths:
       - path: /bolt(/|$)(.*)
         backend:
           serviceName: {{ template "neo4j.fullname" . }}
           servicePort: 7687
