apiVersion: v1
kind: Service
metadata:
  name: service-tibero-sd
spec:
  type: NodePort
  selector:
    app: tibero-sd
  ports:
    - name: tbsd-lsnr
      nodePort: 30866
      port: 8001
      protocol: TCP
      targetPort: 8000
    - name: tbsd-proxy
      nodePort: 30804
      port: 3001
      protocol: TCP
      targetPort: 3000
